#!/bin/bash

#
# This script builds the arena_camera_ros2_docker images locally
# Under most circumstances you should pull the docker images
# automatically generated by Gitlab CI
#

VERSION="0.0.1"

IMAGE_ROOT=registry.gitlab.com/apl-ocean-engineering/arena_camera_ros2
GIT_SHA=$(git describe --always --dirty)

docker build --target build_image \
        --progress plain \
        -t ${IMAGE_ROOT}:build-${VERSION} \
        -t ${IMAGE_ROOT}:build-${GIT_SHA} \
        -t ${IMAGE_ROOT}:build-latest \
        .

BUILD_IMAGE=${IMAGE_ROOT}${BUILD_STEM}
docker build \
        --progress plain \
        ${BUILD_ARGS} --progress plain \
        -t ${IMAGE_ROOT}:${VERSION} \
        -t ${IMAGE_ROOT}:${GIT_SHA} \
        -t ${IMAGE_ROOT}:latest \
        .