name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  CLANG_TIDY: true

jobs:
  ros_industrial_ci:
    name: Run ROS2 Industrial CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env:
          - IMAGE: iron-ci
            ROS_DISTRO: iron
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ROS Industrial CI
        uses: ros-industrial/industrial_ci@master
        env:
          DOCKER_IMAGE: ghcr.io/apl-ocean-engineering/arena_camera_ros2:${{ matrix.env.IMAGE }}
          CXXFLAGS: >-
            -Wall -Wextra -Wpedantic -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls
          CC: ${{ env.CLANG_TIDY && 'clang' }}
          CXX: ${{ env.CLANG_TIDY && 'clang++' }}
